# config.yaml
data:
  csv: Data/market/mkt_ADBE.csv #input
  # csv: Data/apple/MBP_market.csv
  # csv: sub_data.csv
  symbol: batch # put batch when working with several symbols 
  tz_utc: true
  time_col: ts_event 
  resample:
    rule: "30min"     # ex: "30min", "1h", "15min" ; laisse vide/omets pour désactiver
    label: "right"     # "left" ou "right" -> timestamp du bucket
    closed: "left"    # "left" ou "right" -> quels bords sont inclus
    drop_na: true     # drop des buckets incomplets (sans open/close)

output:
  dir: ./dataset_out_ts
  batch_dir: ./dataset_out_ts/batch #only activate when working with several ticker

splits:
  # Use ISO dates; timezone optional. If omitted, we treat as UTC midnight.
  train_end: 2024-12-09
  val_end: 2025-04-09

labels:
  horizons: [1]  #Number of days
  in_sample: false
  median_window: 100

deseasonalization:
  mode: none    # none | robust_train | robust_expanding
  bucket: minute        # minute | hour

images:  
  encoder: ts_vol # - heatmap | ts_vol | ts_ohlc | recurrence | gaf
  windows: [26]          # window length in bars for sampling cadence (keep 26)
  step: 26               # stride in bars between images: 13 ≈ 1 image/day on 30-min RTH; 26 = non-overlap
  ts_ma_window: 48       # moving average window (in bars) drawn on the top panel
  size: 
    width: 256
    height: 256
    dpi: 100
  alignment: 
    enabled: true
    anchor_time: "14:00"
    anchor_tz: "UTC"
  session:
    enforce_end_at_close: true      # ← activer le filtre
    tz: America/New_York            # timezone de référence (DST géré)
    open: "09:30"                   # informatif (inutile pour le check)
    close: "16:00"                  # l’heure de clôture
    bar_label: end                  # "end" si timestamp = fin de bougie, "start" sinon
  grid:
    required_points: 26             # (optionnel) 0 ou null pour ne pas imposer la taille

  ts_overlays:
    top:
      show_ma: true          # show the moving average on the top panel
      show_bbands: true      # draw Bollinger bands on the volatility line
      bb_window: 13
      bb_nstd: 2.0
    bottom:
      panel: volume             # volume | rsi | none
      rsi_window: 14
      rsi_source: vol   # vol | close
    style:
      fg: white
      bg: black
    day_separators:
      enabled: true
      label: true
      color: "#888888"
      alpha: 0.5
      linewidth: 0.8
      label_kind: number    # number | abbr | name
    
  recurrence:
    series: vol         # vol | close | median_hist | ...
    normalize: zscore   # zscore | minmax | none
    metric: euclidean
    epsilon_mode: quantile   # quantile | fixed | none
    epsilon_q: 0.10           # ~10% density if binarize=True
    epsilon_value: null       # use if epsilon_mode=fixed
    binarize: true
    cmap: gray
    invert: true

  gaf:
    mode: gasf           # gasf | gadf
    normalize: minmax    # minmax | zscore | none
    cmap: viridis
    invert: false

  # heatmap:
  #   mode: greyscale      # colormap | rgb
  #   cmap: viridis
  #   vmin: null          # put numbers to enforce global scale (e.g., 0.0)
  #   vmax: null

evaluation:
  embargo_steps: 0      # e.g., 128 + max(horizons)
  no_overlap: false     # if true, step becomes max(images.windows)

training:
  seed: 42
  device: auto           # auto | cuda | cpu | mps
  model: resnet18        # resnet18 | resnet50
  pretrained: true
  num_classes: 2
  epochs: 20
  batch_size: 64
  num_workers: 4
  lr: 1e-3
  weight_decay: 1e-3
  dropout: 0.5           # dropout rate for final layer
  optimizer: adamw       # adamw | sgd
  scheduler: cosine      # none | cosine | step
  step_size: 10          # (if scheduler=step)
  gamma: 0.1             # (if scheduler=step)
  use_amp: true
  monitor: val_f1        # val_f1 | val_loss
  patience: 7
  save_dir: runs/exp1
  normalize: imagenet    # imagenet | null
  augment: true
  prefer_days: true
  return_meta: true
  balanced_sampler: false
  class_weights: true    # if true: Weight cross entropy by inverse frequency
  show_confusion: true      # false to desactivate
  normalize_confusion: false  # true ro display in proportions