# config.yaml
data:
  csv: Data/apple/MBP_market.csv
  # csv: sub_data.csv
  symbol: AAPL
  tz_utc: true
  time_col: ts_event 
  resample:
    rule: "30min"     # ex: "30min", "1h", "15min" ; laisse vide/omets pour désactiver
    label: "right"     # "left" ou "right" -> timestamp du bucket
    closed: "left"    # "left" ou "right" -> quels bords sont inclus
    drop_na: true     # drop des buckets incomplets (sans open/close)

output:
  dir: ./dataset_out_ts

splits:
  # Use ISO dates; timezone optional. If omitted, we treat as UTC midnight.
  train_end: 2025-08-15
  val_end: 2025-08-20

labels:
  horizons: [1, 2]
  median_window: 100

deseasonalization:
  mode: none    # none | robust_train | robust_expanding
  bucket: hour        # minute | hour

images: # Use 30min bucket / use only market data 
  encoder: ts_vol  # heatmap | ts_vol | ts_ohlc | recurrence | gaf
  windows: [26]
  step: 26               # set to window size for no overlap
  ts_ma_window: 48
  size:
    width: 256
    height: 256
    dpi: 100
  alignment:
    enabled: true
    anchor_time: "14:00"   # HH:MM interprété dans anchor_tz
    anchor_tz: "UTC"  

  ts_overlays:
    top:
      show_ma: true          # show the moving average on the top panel
      show_bbands: true      # draw Bollinger bands on the volatility line
      bb_window: 13
      bb_nstd: 2.0
    bottom:
      panel: volume             # volume | rsi | none
      rsi_window: 14
      rsi_source: vol   # vol | close
    style:
      fg: white
      bg: black
    day_separators:
      enabled: true
      label: true
      color: "#888888"
      alpha: 0.5
      linewidth: 0.8
      label_kind: number    # number | abbr | name
    
  recurrence:
    series: vol         # vol | close | median_hist | ...
    normalize: zscore   # zscore | minmax | none
    metric: euclidean
    epsilon_mode: quantile   # quantile | fixed | none
    epsilon_q: 0.10           # ~10% density if binarize=True
    epsilon_value: null       # use if epsilon_mode=fixed
    binarize: true
    cmap: gray
    invert: true

  gaf:
    mode: gasf           # gasf | gadf
    normalize: minmax    # minmax | zscore | none
    cmap: viridis
    invert: false

  # heatmap:
  #   mode: greyscale      # colormap | rgb
  #   cmap: viridis
  #   vmin: null          # put numbers to enforce global scale (e.g., 0.0)
  #   vmax: null

evaluation:
  embargo_steps: 0      # e.g., 128 + max(horizons)
  no_overlap: false     # if true, step becomes max(images.windows)